import { Product, Category, Review } from '../types';

export const categories: Category[] = [
  { id: 1, name: 'Men', slug: 'men' },
  { id: 2, name: 'Women', slug: 'women' },
  { id: 3, name: 'Kids', slug: 'kids' },
  { id: 4, name: 'Accessories', slug: 'accessories' },
  { id: 5, name: 'Gifts', slug: 'gifts' },
  { id: 6, name: 'Lungi', slug: 'lungi' },
  { id: 7, name: 'Dhoti', slug: 'dhoti' },
];

const getCategory = (slug: string): Category => {
    return categories.find(c => c.slug === slug) || categories[0];
};

const reviews: Review[] = [
    { id: 1, author: 'Ramesh K.', rating: 5, comment: 'Excellent quality and very comfortable.' },
    { id: 2, author: 'Suresh P.', rating: 4, comment: 'Good value for money. Color is vibrant.' },
    { id: 3, author: 'Anitha', rating: 5, comment: 'Soft material, my husband loves it!' },
];

export const products: Product[] = [
  {
    id: 1,
    name: 'Classic Checkered Lungi',
    slug: 'classic-checkered-lungi',
    category: getCategory('lungi'),
    gender: 'Men',
    price: 499,
    originalPrice: 799,
    images: ['https://picsum.photos/seed/product1/800/800', 'https://picsum.photos/seed/product1-2/800/800', 'https://picsum.photos/seed/product1-3/800/800'],
    description: 'A timeless classic, this checkered lungi is made from 100% pure Komarapalayam cotton, known for its softness and durability. Perfect for daily wear.',
    details: ['100% Cotton', 'Machine Washable', '2.25 meters length', 'Colorfast guarantee'],
    reviews: reviews.slice(0, 2),
    rating: 4.5,
    reviewCount: 2,
  },
  {
    id: 2,
    name: 'Pure White Temple Dhoti',
    slug: 'pure-white-temple-dhoti',
    category: getCategory('dhoti'),
    gender: 'Men',
    price: 899,
    originalPrice: 1199,
    images: ['https://picsum.photos/seed/product2/800/800', 'https://picsum.photos/seed/product2-2/800/800'],
    description: 'Feel divine in our pure white temple dhoti. Woven with care and precision, it offers unparalleled comfort and a graceful drape for all your spiritual occasions.',
    details: ['Premium Weave Cotton', 'Hand Wash Recommended', '4 meters length', 'Slightly starched for a crisp look'],
    reviews: [reviews[2]],
    rating: 5,
    reviewCount: 1,
  },
  {
    id: 3,
    name: 'Komarapalayam Silk Lungi',
    slug: 'komarapalayam-silk-lungi',
    category: getCategory('lungi'),
    gender: 'Men',
    price: 1599,
    originalPrice: 2199,
    images: ['https://picsum.photos/seed/product3/800/800', 'https://picsum.photos/seed/product3-2/800/800'],
    description: 'Exquisite silk-blend lungi from the master weavers of Komarapalayam. Features a beautiful golden border for a regal touch.',
    details: ['Silk-Cotton Blend', 'Dry Clean Only', '2.5m length', 'Intricate Zari Border'],
    reviews: [],
    rating: 0,
    reviewCount: 0,
  },
   {
    id: 4,
    name: 'Striped Casual Lungi',
    slug: 'striped-casual-lungi',
    category: getCategory('lungi'),
    gender: 'Men',
    price: 550,
    originalPrice: 699,
    images: ['https://picsum.photos/seed/product6/800/800', 'https://picsum.photos/seed/product6-2/800/800'],
    description: 'A modern take on the traditional lungi with stylish stripes. Perfect for lounging at home or a casual outing.',
    details: ['100% Cotton', 'Machine Washable', '2.25 meters length', 'Modern striped pattern'],
    reviews: [reviews[1]],
    rating: 4,
    reviewCount: 1,
  },
  {
    id: 5,
    name: 'Gold Border Wedding Dhoti',
    slug: 'gold-border-wedding-dhoti',
    category: getCategory('dhoti'),
    gender: 'Men',
    price: 1299,
    originalPrice: 1799,
    images: ['https://picsum.photos/seed/product7/800/800', 'https://picsum.photos/seed/product7-2/800/800'],
    description: 'A premium dhoti for weddings and special functions. The rich gold border adds a touch of grandeur to your look.',
    details: ['Premium Cotton', 'Hand Wash', '4.5 meters length', 'Wide gold zari border'],
    reviews: [],
    rating: 0,
    reviewCount: 0,
  },
  {
    id: 6,
    name: 'Loose Fit Hoodie',
    slug: 'loose-fit-hoodie',
    category: getCategory('men'),
    gender: 'Unisex',
    price: 1200,
    originalPrice: 2000,
    images: ['https://picsum.photos/seed/hoodie1/800/800', 'https://picsum.photos/seed/hoodie1-2/800/800'],
    description: 'A comfortable and stylish loose fit hoodie, perfect for any casual occasion.',
    details: ['80% Cotton, 20% Polyester', 'Machine Washable', 'Front Pouch Pocket'],
    reviews: [],
    rating: 4.8,
    reviewCount: 15,
  },
  {
    id: 7,
    name: 'Patterned Scarf',
    slug: 'patterned-scarf',
    category: getCategory('accessories'),
    gender: 'Unisex',
    price: 880,
    originalPrice: 1000,
    images: ['https://picsum.photos/seed/scarf1/800/800', 'https://picsum.photos/seed/scarf1-2/800/800'],
    description: 'A soft, patterned scarf to complete your winter look.',
    details: ['100% Viscose', 'Hand Wash Only', 'Fringed Edges'],
    reviews: [],
    rating: 4.5,
    reviewCount: 12,
  },
  {
    id: 8,
    name: 'Relaxed Fit Zip Jacket',
    slug: 'relaxed-fit-zip-jacket',
    category: getCategory('men'),
    gender: 'Men',
    price: 1500,
    originalPrice: 2200,
    images: ['https://picsum.photos/seed/jacket1/800/800', 'https://picsum.photos/seed/jacket1-2/800/800'],
    description: 'A lightweight and relaxed fit zip jacket for everyday wear.',
    details: ['100% Nylon Shell', 'Polyester Lining', 'Zippered Pockets'],
    reviews: [],
    rating: 4.7,
    reviewCount: 25,
  },
  {
    id: 9,
    name: 'Rib-Knit Hat',
    slug: 'rib-knit-hat',
    category: getCategory('accessories'),
    gender: 'Unisex',
    price: 750,
    originalPrice: 950,
    images: ['https://picsum.photos/seed/hat1/800/800', 'https://picsum.photos/seed/hat1-2/800/800'],
    description: 'A classic rib-knit hat to keep you warm and stylish.',
    details: ['100% Acrylic', 'One Size Fits Most', 'Turn-up Brim'],
    reviews: [],
    rating: 4.9,
    reviewCount: 30,
  },
  {
    id: 10,
    name: 'Lightweight Puffer Jacket',
    slug: 'lightweight-puffer-jk',
    category: getCategory('women'),
    gender: 'Women',
    price: 1200,
    originalPrice: 1800,
    images: ['https://picsum.photos/seed/puffer1/800/800', 'https://picsum.photos/seed/puffer1-2/800/800'],
    description: 'Stay warm without the bulk in this lightweight puffer jacket.',
    details: ['Water-resistant fabric', 'Down-alternative fill', 'Packable design'],
    reviews: [],
    rating: 4.6,
    reviewCount: 18,
  },
  {
    id: 11,
    name: '2-Pack Cotton Hats',
    slug: '2-pack-cotton-hats',
    category: getCategory('kids'),
    gender: 'Kids',
    price: 880,
    originalPrice: 1200,
    images: ['https://picsum.photos/seed/kidhat1/800/800', 'https://picsum.photos/seed/kidhat2/800/800'],
    description: 'A convenient two-pack of soft cotton hats for kids.',
    details: ['100% Organic Cotton', 'Stretchy and comfortable', 'Assorted colors'],
    reviews: [],
    rating: 5,
    reviewCount: 22,
  },
  {
    id: 12,
    name: 'Chunky Trainers',
    slug: 'chunky-trainers',
    category: getCategory('women'),
    gender: 'Women',
    price: 1500,
    originalPrice: 2500,
    images: ['https://picsum.photos/seed/trainers1/800/800', 'https://picsum.photos/seed/trainers1-2/800/800'],
    description: 'Make a statement with these trendy chunky trainers.',
    details: ['Faux leather upper', 'Chunky rubber sole', 'Padded collar for comfort'],
    reviews: [],
    rating: 4.3,
    reviewCount: 9,
  },
  {
    id: 13,
    name: 'Kids Graphic Tee',
    slug: 'kids-graphic-tee',
    category: getCategory('kids'),
    gender: 'Kids',
    price: 450,
    originalPrice: 600,
    images: ['https://picsum.photos/seed/kidstee/800/800'],
    description: 'A fun and comfortable graphic tee for kids.',
    details: ['100% Cotton', 'Machine Washable', 'Playful front graphic'],
    reviews: [],
    rating: 4.8,
    reviewCount: 14,
  },
  {
    id: 14,
    name: 'Leather Crossbody Bag',
    slug: 'leather-crossbody-bag',
    category: getCategory('accessories'),
    gender: 'Women',
    price: 1800,
    originalPrice: 2400,
    images: ['https://picsum.photos/seed/bag1/800/800', 'https://picsum.photos/seed/bag1-2/800/800'],
    description: 'A versatile and stylish leather crossbody bag.',
    details: ['Genuine Leather', 'Adjustable strap', 'Multiple compartments'],
    reviews: [],
    rating: 4.9,
    reviewCount: 19,
  },
  {
    id: 15,
    name: 'Women\'s High-Waist Jeans',
    slug: 'womens-high-waist-jeans',
    category: getCategory('women'),
    gender: 'Women',
    price: 1600,
    originalPrice: 2200,
    images: ['https://picsum.photos/seed/jeans1/800/800'],
    description: 'Flattering high-waist jeans with a comfortable stretch.',
    details: ['Cotton-elastane blend', 'Five-pocket styling', 'Straight leg fit'],
    reviews: [],
    rating: 4.5,
    reviewCount: 28,
  }
];

export const getProductBySlug = (slug: string): Product | undefined => {
    return products.find(p => p.slug === slug);
}

export const getProductsByCategory = (categorySlug: string): Product[] => {
    if (categorySlug === 'all') return products;

    if(['men', 'women', 'kids'].includes(categorySlug)) {
        return products.filter(p => p.gender.toLowerCase() === categorySlug || p.gender === 'Unisex');
    }

    const category = categories.find(c => c.slug === categorySlug);
    if (!category) return [];
    return products.filter(p => p.category.id === category.id);
}

export const getRelatedProducts = (currentProductId: number): Product[] => {
    return products.filter(p => p.id !== currentProductId).slice(0, 4);
}